setting:
  request: # 网络请求设置
    timeout: 10 # 超时设置
    ssl: false # ssl设置

  gitee_friends_links: # gitee友链配置
    enable: false
    owner: Zfour
    repo: friends
    state: open

  github_friends_links: # github友链配置
    enable: true
    owner: xaoxuu
    repo: friends
    state: open

  user_info: # 用户信息配置
    - title
    - description
    - screenshot
    - url
    - avatar
    - group
